version: "3.5"

services:
  restapi:
    image: lukeshaydocker/route-rating-rest-api:latest
    restart: always
    container_name: rest-api
    ports:
      - 5000:8080
    working_dir: /app
    environment:
      - REST_API_JWT_SECRET=REST_API_JWT_SECRET
      - REST_API_REFRESH_SECRET=REST_API_REFRESH_SECRET
      - DIGITAL_OCEAN_ACCESS_KEY=DIGITAL_OCEAN_ACCESS_KEY
      - DIGITAL_OCEAN_SECRET_KEY=DIGITAL_OCEAN_SECRET_KEY
      - GOOGLE_RECAPTCHA_TOKEN=$GOOGLE_RECAPTCHA_TOKEN
      - REST_API_DB_URL=jdbc:postgresql://postgres:5432/routerating
      - REST_API_DB_PASSWORD=password
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    container_name: rest-api-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: routerating
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
