version: "3.5"

services:
  postgres:
    image: postgres
    container_name: rest-api-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=routerating
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  db-data:
    driver: local
