name: Build master
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  merge-PR:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: lukeshaydocker/route-rating-rest-api
      SHA: ${GITHUB_SHA::7}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.5' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: ./scripts/build.sh
      - run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - run: docker build -t ${{ env.DOCKER_REPO }}:${{ env.SHA }} -t ${{ env.DOCKER_REPO }}:latest .
      - run: docker push ${{ env.DOCKER_REPO }}:${{ env.SHA }}
      - run: docker push ${{ env.DOCKER_REPO }}:latest